### ISSUE TITLE
Cannot read properties of undefined (reading 'ref')

### ISSUE THREAD

**Issue by hosein74** [astahmer/openapi-zod-client#157]
when I want use tag-file in --group-strategy  or 'method-file' in command like this : 

command  : yarn openapi-zod-client "api.json" -o  "src/api" --group-strategy  "tag-file" -a

this error occure:

$ C:\Users\me\myproject\node_modules\.bin\openapi-zod-client api.json -o src/api --group-strategy tag-file -a
Retrieving OpenAPI document from api.json
C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2266
          (_depsGraphs$deepDepen5 = depsGraphs.deepDependencyGraph[result.resolver.resolveSchemaName(schemaName).ref]) === null || _depsGraphs$deepDepen5 === void 0 ? void 0 : _depsGraphs$deepDepen5.forEach(function (transitiveRef) {
                                                                                                                ^

TypeError: Cannot read properties of undefined (reading 'ref')
    at C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2266:113
    at Array.forEach (<anonymous>)
    at C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2260:42    at Array.forEach (<anonymous>)
    at getZodClientTemplateContext (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2214:20)
    at _callee$ (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2345:20)
    at tryCatch (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.    at Generator.<anonymous> (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:158:22)
    at Generator.next (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:102:21)
    at asyncGeneratorStep (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:345:24)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Usersme\myproject> yarn openapi-zod-client "api.json" -o  "src/api" --group-strategy  "tag-file" -a
yarn run v1.22.19
$ C:\Users\me\myproject\node_modules\.bin\openapi-zod-client api.json -o src/api --group-strategy tag-file -a
Retrieving OpenAPI document from api.json
C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2266
          (_depsGraphs$deepDepen5 = depsGraphs.deepDependencyGraph[result.resolver.resolveSchemaName(schemaName).ref]) === null || _depsGraphs$deepDepen5 === void 0 ? void 0 : _depsGraphs$deepDepen5.forEach(function (transitiveRef) {
                                                                                                                ^

TypeError: Cannot read properties of undefined (reading 'ref')
    at C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2266:113
    at Array.forEach (<anonymous>)
    at C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2260:42    at Array.forEach (<anonymous>)
    at getZodClientTemplateContext (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2214:20)
    at _callee$ (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:2345:20)
    at tryCatch (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:77:17)
    at Generator.<anonymous> (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:158:22)
    at Generator.next (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:102:21)
    at asyncGeneratorStep (C:\Users\me\myproject\node_modules\openapi-zod-client\dist\generateZodClientFromOpenAPI-0daa4355.cjs.dev.js:345:24)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by astahmer** [comment]
can you provide a minimal reproduction here ? https://openapi-zod-client.vercel.app/ 
you can hit ctrl+s to save & share the link

or just paste your relevant json/yaml part here

**Comment by hosein74** [comment]
The error occurs here as well : picture in attachment
And now I understand that this error does not occur when the json file size
becomes smaller But this problem occurs when the size of the file is large
error copied from console :
TypeError: Cannot read properties of undefined (reading 'ref')
    at index.2b3b4cd4.js:1176:8690
    at Array.forEach (<anonymous>)
    at index.2b3b4cd4.js:1176:8552
    at Array.forEach (<anonymous>)
    at YQe (index.2b3b4cd4.js:1176:7843)
    at index.2b3b4cd4.js:2463:5572
    at index.2b3b4cd4.js:453:5477
    at Array.reduce (<anonymous>)
    at jde (index.2b3b4cd4.js:453:5387)
    at k (index.2b3b4cd4.js:453:10518)



‫‪Alexandre Stahmer‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۲ ژوئن
۲۰۲۳ ساعت ۱۲:۲۳ نوشت:‬

**Comment by astahmer** [comment]
could you paste the openapi JSON ?
and if that error doesnt happen on the playground, maybe you need to upgrade the library version ?

**Comment by hosein74** [comment]
i pasted it ,and  error accured

**Comment by filipbekic01** [comment]
I have same error on my schema, it's complex and private company source. It only happens only for file strategies. Other works well.

**Comment by ezze** [comment]
@astahmer Here is a minimal `swagger.json` I was able to reproduce the problem with:

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "SberCity CRM API",
    "version" : "v1"
  },
  "servers" : [ {
    "url" : "http://localhost:37629",
    "description" : "Generated server url"
  } ],
  "paths" : {
    "/api/v1/settlement" : {
      "post" : {
        "tags" : [ "settlement-controller" ],
        "operationId" : "create_7",
        "parameters" : [ {
          "name" : "createDto",
          "in" : "query",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/SettlementCreateRequest"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SettlementResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "SettlementResponse" : {
        "required": [ "id", "name" ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Идентификатор",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "description": "Название заселения"
          }
        }
      },
      "SettlementCreateRequest" : {
        "required" : [ "dealId", "responsibleUserId" ],
        "type" : "object",
        "properties" : {
          "dealId" : {
            "type" : "integer",
            "format" : "int32"
          },
          "responsibleUserId" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}
```

I also tried to [dereference JSON schema](https://apitools.dev/swagger-parser/docs/swagger-parser.html#dereferenceapi-options-callback) but result is still the same (schema is valid but I get the error in the topic):

```typescript
  const openApiSchemaPath = path.resolve(rootPath, 'swagger-test.json');
  const prettierConfig = await resolveConfig(rootPath);

  const schema = await SwaggerParser.bundle(openApiSchemaPath);
  const dereferencedSchema = await SwaggerParser.dereference(schema);
  try {
    await SwaggerParser.validate(dereferencedSchema);
    console.log('Schema is valid');
  } catch (e) {
    console.error(e);
  }

  await generateZodClientFromOpenAPI({
    openApiDoc: dereferencedSchema as OpenAPIObject,
    distPath: outputFilePath,
    prettierConfig,
    options: {
      groupStrategy: 'method-file',
      withAlias: true
    }
  });
```

**Comment by astahmer** [comment]
got it, thanks for the investigation ! 
feel free to send a PR as I probably won't be able to contribute, being busy maintaining Panda CSS

**Comment by ezze** [comment]
@astahmer Please, take a look: https://github.com/astahmer/openapi-zod-client/pull/251
